#!/bin/bash

echo "🚀 ARA Voice Form - Convex Deployment (convexpo pattern)"
echo "======================================================"
echo ""

echo "📋 Following convexpo structure:"
echo "✅ convex/convex.config.ts - App configuration"
echo "✅ convex/schema.ts - Database schema" 
echo "✅ convex/healthCheck.ts - Health check endpoint"
echo "✅ convex/api.ts - AI integration functions"
echo "✅ providers/ConvexProvider.tsx - React provider"
echo ""

echo "🔧 STEP 1: Configure Convex Project"
echo "==================================="
echo "Run this command manually:"
echo "npx convex dev"
echo ""
echo "This will:"
echo "1. Create/link your Convex project"
echo "2. Generate TypeScript types in convex/_generated/"
echo "3. Push schema to development deployment"
echo ""

echo "🌐 STEP 2: Deploy to Production"
echo "==============================="
echo "After configuration, run:"
echo "npx convex deploy --yes"
echo ""

echo "🔑 STEP 3: Set Environment Variables"
echo "===================================="
echo "Set these in your Convex dashboard:"
echo "npx convex env set OPENROUTER_API_KEY your_key_here"
echo "npx convex env set ELEVENLABS_API_KEY your_key_here"
echo ""

echo "📱 STEP 4: Update Mobile App"
echo "============================"
echo "1. Add to .env:"
echo "   EXPO_PUBLIC_CONVEX_URL=https://your-project.convex.cloud"
echo ""
echo "2. Update app/_layout.tsx to use ConvexProvider:"
echo "   import ConvexProvider from '@/providers/ConvexProvider';"
echo ""
echo "3. Replace tRPC calls with Convex functions:"
echo "   - trpc.ai.generateText → useMutation('api.api.generateText')"
echo "   - trpc.users.create → useMutation('api.users.create')"
echo ""

echo "📊 Available Convex Functions:"
echo "=============================="
echo "Database:"
echo "- api.users.create - Create user"
echo "- api.users.get - Get user by email"  
echo "- api.contracts.create - Create contract"
echo "- api.contracts.list - List user contracts"
echo ""
echo "AI Integration:"
echo "- api.api.generateText - OpenRouter AI text generation"
echo "- api.api.transcribeAudio - ElevenLabs speech-to-text"
echo "- api.api.smartEdit - Context-aware field editing"
echo "- api.healthCheck.get - Backend health check"
echo ""

echo "🔄 Migration from tRPC to Convex:"
echo "================================="
echo "Before: trpc.example.useQuery()"
echo "After:  useQuery('api.example.get')"
echo ""
echo "Before: trpc.example.useMutation()"
echo "After:  useMutation('api.example.create')"
echo ""

echo "✅ Ready for Convex deployment!"
echo "Run 'npx convex dev' to get started"